server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          在GitHub上面去uri的地址上找search-paths的label分支
          uri: https://github.com/2367076952/springcloud-config.git
          ####搜索目录
          search-paths:
            - springcloud-config
#          username: 2367076952
#          password: SHA256:CHaRVTqMuSCh6hi1xGz6EN2Yx3Vfg2kKb96CLl510fs
          #          读取分支
#        default-label: master

      label: newbranch


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
